# SPDX-FileCopyrightText: 2024 splode contributors <https://github.com/ash-project/splode/graphs.contributors>
#
# SPDX-License-Identifier: MIT

---
updates:
  - directory: /
    package-ecosystem: mix
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
version: 2
